server:
	cd src && javac ChatServer.java && java ChatServer 12345
client1:
	cd src/Client_1 && javac ChatClient.java && java ChatClient 127.0.0.1 12345
client2:
	cd src/Client_2 && javac ChatClient.java && java ChatClient 127.0.0.1 12345